---
abstract: 'A sorted list of English stop words'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0.96
  Test::Pod: 1.44
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4002, CPAN::Meta::Converter version 2.120630'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-EN-StopWordList
provides:
  Lingua::EN::StopWordList:
    file: lib/Lingua/EN/StopWordList.pm
    version: 1.00
requires:
  strict: 1.04
  warnings: 1.12
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 1.00
