---
abstract: 'A sorted list of English stop words'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: '1.001014'
  Test::Pod: '1.48'
configure_requires:
  Module::Build: '0.4211'
dynamic_config: 1
generated_by: 'Module::Build version 0.4211, CPAN::Meta::Converter version 2.143240'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Lingua-EN-StopWordList
provides:
  Lingua::EN::StopWordList:
    file: lib/Lingua/EN/StopWordList.pm
    version: '1.01'
requires:
  strict: '1.04'
  warnings: '1.12'
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: '1.01'
